runtime: python311
entrypoint: gunicorn -b :$PORT run:app
env_variables:
  OPENAI_API_KEY: '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'
  PINECONE_API_KEY: 'b55bf165-bbc7-4bbf-86d7-5e1efc715872'